### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by dwiyomi** [m45rud/ams_native#1]
file database_backup.php dan database_restore.php tidak ada kak... jadi tidak bisa di running T.T

**Comment by m45rud** [comment]
Itu dokumentasi yang lama, sudah saya perbarui dokumentasinya. file sebenarnya backup.php dan restore.php silakan dicoba kembali :)

**Comment by dwiyomi** [comment]
Iya kak, udah ketemu wkwkwk terimakasih.. tapi yaa saya kok ga bisa login
T.T

Di databasenya saya tambah user, tp dibuat login ga bisa. Gimana ya
solusinya, saya masih belajar

**Comment by m45rud** [comment]
user dan passwordnya admin.
